### ISSUE TITLE
Wonderful Work , does it support CogVideoX5B?

### ISSUE THREAD

**Issue by bendanzzc** [Vchitect/FasterCache#3]

**Comment by ChenyangSi** [comment]
We're implementing FasterCache on CogVideoX5B and Mochi.  Please stay tuned for updates! Thanks!

**Comment by cszy98** [comment]
Hi, the script for CogVideoX-5b has been updated. Before using it, you need to download the corresponding model and modify the relevant path in configs/cogvideox/fastercache_sample_5b.yaml. Run scripts/cogvideox/fastercache_sample_cogvideox5b.sh for inference. 

The acceleration script for Mochi will be updated soon. Thank you for your interest.

**Comment by cszy98** [comment]
Hi, we have implemented the script for Mochi. Thank you for your interest.
