### ISSUE TITLE
Does fastercache support multi-gpu cogvideox?

### ISSUE THREAD

**Issue by fishelegs** [Vchitect/FasterCache#4]
Does fastercche support multi-gpu cogvideox 2B inference?

Thanks!

**Comment by Sonny529** [comment]
We have implemented faster CogVideo-2B inference with 2,4 or 8 GPUs in the new script scripts/cogvideox/fastercache_sample_cogvideox_multi_device.sh.
The original script fastercache_sample_cogvideox.sh now supports batched inference if you run it with multiple devices and a txt input.
